ARG NODE_VERSION=20.9.0
ARG ALPINE_VERSION=3.19.1

FROM node:${NODE_VERSION}-alpine AS node

FROM alpine:${ALPINE_VERSION}

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin




WORKDIR /koksmat/.koksmat/web
COPY . .
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build

EXPOSE 4444

CMD [ "pnpm","start"]